### ISSUE TITLE
Structured dictionary option for DidYouMean

### ISSUE THREAD

**Issue by obromios** [yuki24/did_you_mean#118]
I am the author of this [enhancement](https://github.com/rspec/rspec-core/pull/2601)  to ```rspec``` which uses your ::DidYouMean::SpellChecker api to provides a did_you_mean functionality to ```rspec``` commands.

The typical string in this application is long, say 40 to 80 characters, so with the current constants, too many suggestions can be returned..  One quick fix for this might be a modification to your api to allow optional arguments for the initialiser e.g threshold: 0.7, weight: 0.1.  There may be other applications that benefit from being able to set different thresholds etc. 

At a more fundamental level, the DidYouMean algorithm does not make any assumptions about the structure of the string. This is good if there is no a prior information about the structure. 

However, the strings ```rspec``` uses are file paths and so have a known structure. Each path e.g. spec/models/user_spec.rb has relatively few choices at each node in the chain. As well, the choices have typically a small number of characters e.g. after spec/ the choices might be '[models, controllers, features]'. I have started work on an algorithm  with the aim of exploiting this structure to give superior results.  This code is re-using some your existing code so would fit well into  your gem.

A DidYouMean api that exploits the structure of a dictionary is likely to be useful in applications other than ```rspec```, perhaps even in the code that ruby uses to load a file.

I would suggest two PRs The first would be one to add optional argument for the constants in the current spell checker api.  

The second PR would be to develop a checker that exploits dictionary structure.  This could take time to develop. I am not sure if this should be an option on the existing spell checker api or a new api.

**Comment by yuki24** [comment]
Thanks for your suggestion. This makes total sense, and I'd like to improve the experience. I think we will be able to take advantage of it in other gems like Rake:

<img width="634" alt="Screen Shot 2018-06-20 at 21 39 56" src="https://user-images.githubusercontent.com/386234/54074067-151a9980-425c-11e9-98a1-54f930bdb010.png">

In this case the entire task name is taken into account even though rake task names have a consistent naming structure. I wonder if a separate spell checker would make sense, for example:

```ruby
checker = DidYouMean::PathSpellChecker.new(dictionary: spec_file_paths, divider: "/")

checker.correct("spec/controller/userrr_sepc.rb")
# => ["spec/controller/user_spec.rb"]

checker = DidYouMean::PathSpellChecker.new(dictionary: rake_task_names, divider: ":")

checker.correct("parallel:preprare")
# => ["parallel:prepare"]
```

One reason why I would like a separate spell checker (that of course could extend or re-use the existing one) is that it is easy to add one optimization and break other optimizations. While an extra option would make it easy to isolate them, I don't belive a separate constant would make the API less intuitive.

Also, I'm not sure about the name `PathSpellChecker` since it seems to be biased to your original proposal. I wonder if `ScopedSpellChecker` or `NamespacedSpellChecker` is a better name.

>  perhaps even in the code that ruby uses to load a file.

Absolutely. I have been looking into how we could make `require` smarter, and this will certainly be useful when implementing it. Though right now this is very hard to implement and make it performant due to how Ruby looks up a file (linear search).

cc @xtina-starr

**Comment by yuki24** [comment]
Actually, adding an `jaro_winkler_threashold` option might be just enough to make it accurate, since these confusing suggestions are coming from the prefix-based optimizaiton and we could simply specify `jaro_winkler_threashold: 1` (exact match) and the Leveshtein distance should give us more accurate suggestions.

**Comment by obromios** [comment]
Thank you for your interest in my suggestion.

- I suspect prefix optimisation also causes problems with the rspec spell checking. 
- I agree that rake is another example that may benefit from a structured dictionary approach.
- In regard to alternative names to ```PathSpellChecker```, perhaps ```TreeSpellChecker```  because  I think [tree](https://en.wikipedia.org/wiki/Tree_(graph_theory)) describes both a path name and the rake structure.
- I agree that that by varying the thresholds, you can improve the performance for both rake and rspe applications.  

I propose the following method of collaboration on this:

1. You improve the performance of both the rake and rspec type application by changing the thresholds. You are much more experienced than me with the existing algorithm and so would would a much better job than me. This would then produce solid a performance benchmarks against which we can test the structured algorithm.

2. I develop the version of the structured algorithm.

3. We jointly develop a list of misspellings to test both approaches.

Does this make sense, or do you think some other approach would be better?

**Comment by obromios** [comment]
I have been thinking about this further, particularly why using knowledge about the structure of dictionary can improve the performance.  Suppose the input string has three mistakes i.e. ```speX/modelX/useX_spec.rb``` instead of ```spec/model/user_spec.rb```.   By splitting it up into the components, and comparing ```speX``` against ```spec``` and ```modelX``` against ```[models, controllers, features]``` you can decide with only a threshold  of a distance of 1,  that the correct path must be ```spec/models```, and then if you look the base names in ```spec/models/``` you can match to ```user_spec.rb``` again with a threshold distance of 1, and it is highly likely there is only one suggestion.  If you tried to correct the string without using knowledge of the structure, you would need a threshold distance of 3, and so are likely to get more than one suggestion.

This is a very rough heuristic,  but gives you an idea of the direction in which I am heading.

Thinking this through also made it clearer to me that I have have to give consideration to the best matching possible when not using the dictionary structure so I can clearly understand the ways that structure can improve things. So if you are too busy to think about this, then I am happy to proceed on both angles.  So, should I do a PR for this, and what name would you like to call the api, I prefer ```TreeSpellChecker```, but am happy to go with any of your ideas on this.

**Comment by yuki24** [comment]
@obromios Thanks for following up, and I'm sorry for not getting back sooner. I don't think I have enough bandwidth to handle that for the time being. It'd be greatly appreciated if you could send PRs.

**Comment by obromios** [comment]
Thank you, I will start working on it.

**Comment by obromios** [comment]
Added with this [commit](https://github.com/yuki24/did_you_mean/commit/63b92df4cb8ebe384dcf34d00a548acc1866fe96).
