### ISSUE TITLE
Levenshtein C

### ISSUE THREAD

**Issue by codenamev** [yuki24/did_you_mean#57]
I see that you are using the [jaro_winkler](https://github.com/tonytonyjan/jaro_winkler) gem for use of the C bindings for the implementation of the formula.  Is there a reason you chose not to use a C implementation for the Levenshtein method?  I have used the [levenshtein-ffi](https://github.com/dbalatero/levenshtein-ffi/blob/master/ext/levenshtein/levenshtein.c) gem for other projects without issue.

**Comment by johnlinvc** [comment]
I think it's because levenshtein-ffi doesn't support unicode strings
https://github.com/dbalatero/levenshtein-ffi#known-issues
># Known Issues
>
> - The C extension uses char* strings, and so Unicode strings will give incorrect distances.

**Comment by yuki24** [comment]
the `jaro_winkler` gem is not a dependency and the `did_you_mean` gem totally works without it. I just use it to only speed up [the evaluation script](https://github.com/yuki24/did_you_mean/blob/master/evaluation/calculator.rb#L32-L38). Adding C extensions makes it harder for other Ruby implementations to work with this gem since some of them are not even written in C.
