### ISSUE TITLE
Why does it require Ruby 2.5.0-dev now?

### ISSUE THREAD

**Issue by nikolay** [yuki24/did_you_mean#96]

**Comment by yuki24** [comment]
I understand this is very annoying, but this is a side-effect of the current release process we follow. Every year we release a new version of the did_you_mean gem right before a new version of Ruby comes out. As a result of this there's a short period of time where `gem update did_you_mean` fails due to the version constraints. As soon as Ruby `2.5.0` becomes available (planned on 25th), this won't be a problem.

We do this to make sure the latest version of the did_you_mean is fully compatible with the latest version of Ruby in trunk. We may change this in the future, but for now please wait until December 25th.

**Comment by Zyphrax** [comment]
That is quite annoying, it seems that 90% of the time that I update my gems I get an error like
`Error installing did_you_mean: .... did_you_mean requires Ruby version ...`

Couldn't you make the new version a [prelease gem](http://guides.rubygems.org/patterns/#prerelease-gems) until ruby has caught up?

**Comment by yuki24** [comment]
The issue is Rubygems not picking up the most recent and compatible version of a gem for a particular Ruby version. Please refer to [the conversation on Rubygems](https://github.com/rubygems/rubygems/issues/454#issuecomment-13815556) for more details as it could arise in any gem that has a `required_ruby_version`.

> Couldn't you make the new version a prelease gem until Ruby has caught up?

I don't think that's ideal. For the last three major versions we always have added something that relies on a new Ruby core API. What this means is that if we had followed this rule, we would have always needed to make a prerelease. This is especially scary when `0.10.0` has a C extension and JRuby also installs DYM. I'll investigate to see if there is any way to make DYM compatible with both the latest Ruby and the last two major versions.

**Comment by Zyphrax** [comment]
@yuki24 Thank you for looking into this.

There must be some way to prevent these error messages. Many users aren't on the latest version of Ruby (especially if it is still a preview Ruby version).

**Comment by Coeur** [comment]
> I'll investigate to see if there is any way to make DYM compatible with both the latest Ruby and the last two major versions.

That sounds like a mandatory step to consider, as we're now one year in the future and Ruby 2.3.x is still the default for latest macOS. People won't update Ruby just for did_you_mean, so better have did_you_mean retro-compatible.

**Comment by yuki24** [comment]
As stated in the release note, the latest version 1.3.0 is compatible with both 2.5 and 2.6. We'll at least try to maintain the backward-compatibility going forward. JRuby will also be added to the build matrix soon.

That being said, the issue is still in Rubygems. Like I said earlier, any gem could cause this if it has a `required_ruby_version` constraint.
